"""Make modern cflib talk to a Crazyflie 1.0.

cflib probes for protocol versioning by sending a link-service SOURCE request
and checking whether the reply starts with the magic string "Bitcraze
Crazyflie". Firmware that predates protocol versioning -- the Crazyflie 1.0 --
answers that channel with a generated byte pattern instead, and cflib does:

    if pk.data[:18].decode('utf8') == 'Bitcraze Crazyflie':

which raises UnicodeDecodeError on those bytes. The exception escapes inside a
port callback, so the `else` branch that sets the protocol version to -1 and
advances the connection sequence never runs, and open_link() blocks forever.

That `else` branch is exactly the legacy path we want: protocol version -1 is
below the >= 4 threshold in TocFetcher, so the TOC is fetched with the V1
commands a Crazyflie 1.0 actually implements.

The fix is to make the magic-string comparison tolerate non-UTF8 payloads.
Patched here rather than in site-packages so it survives reinstalling cflib.
"""
from __future__ import annotations

from cflib.crazyflie.mem import Memory
from cflib.crazyflie.platformservice import (
    LINKSERVICE_SOURCE,
    VERSION_COMMAND,
    VERSION_GET_PROTOCOL,
    PlatformService,
)
from cflib.crtp.crtpstack import CRTPPacket, CRTPPort

MAGIC = b'Bitcraze Crazyflie'

_applied = False


def _crt_service_callback(self, pk) -> None:
    if pk.channel != LINKSERVICE_SOURCE:
        return

    # Compare as bytes. The original decodes to str first, which throws on the
    # arbitrary bytes a Crazyflie 1.0 returns here.
    if bytes(pk.data[:18]) == MAGIC:
        reply = CRTPPacket()
        reply.set_header(CRTPPort.PLATFORM, VERSION_COMMAND)
        reply.data = (VERSION_GET_PROTOCOL,)
        self._cf.send_packet(reply)
    else:
        # Pre-versioning firmware: -1 selects the V1 TOC and logging commands.
        self._protocolVersion = -1
        self._callback()


def _is_legacy(cf) -> bool:
    """True for pre-versioning firmware, which reports protocol version -1."""
    return cf.platform.get_protocol_version() < 0


_orig_mem_refresh = Memory.refresh


def _mem_refresh(self, refresh_done_callback, refresh_failed_cb=None):
    """Skip the memory scan on a Crazyflie 1.0.

    The memory subsystem (CRTP port 4) arrived with the Crazyflie 2.0. A 1.0
    never answers the "how many memories" request, and cflib retries it
    forever, stalling the connection sequence before the parameter TOC is
    fetched. There are no memories to find, so report zero and move on.
    """
    if not _is_legacy(self.cf):
        return _orig_mem_refresh(self, refresh_done_callback, refresh_failed_cb)

    for mem in self.mems:
        try:
            self.mem_read_cb.remove_callback(mem.new_data)
            mem.disconnect()
        except Exception:  # noqa: BLE001 - mirrors upstream's own tolerance here
            pass
    self.mems = []
    self.nbr_of_mems = 0
    self._getting_count = False

    if refresh_done_callback:
        refresh_done_callback()
    return None


def apply() -> None:
    """Install the patches. Safe to call more than once."""
    global _applied
    if not _applied:
        PlatformService._crt_service_callback = _crt_service_callback
        Memory.refresh = _mem_refresh
        _applied = True
